WIP CIR-57 added functionality for querying CIs
ONSdigital/eq-collection-instrument-registry pull request #20
Opened 2023-02-20 12:47 UTC by SriHV

Added functionality for querying CIs

2023-02-20 14:14 UTC, aljaplatt approved these changes

2023-02-20 14:16 UTC, aljaplatt commented
Looks good to me 👍

2023-02-20 15:44 UTC, tidmanmike submitted a review, later dismissed

2023-02-21 09:36 UTC, reach4nk requested changes
Awaiting testing of the endpoint.

2023-02-21 09:40 UTC, mateen-hussain commented on gateway/openapi.yaml
> +#        address: https://http-publish-ci-7u4cmdz5dq-ew.a.run.app -- ons-cir-development
You can remove this comment

2023-02-22 10:35 UTC, reach4nk approved these changes

2023-02-22 16:16 UTC, aljaplatt approved these changes
Good job with the pytest mocking guys, looks good.

2023-02-22 16:18 UTC, aljaplatt commented on handlers/tests/test_search.py
> +    assert items[1] == expected_resp[1], items
Why is items added after expected_resp[1]?

2023-02-23 09:08 UTC, SriHV commented on handlers/tests/test_search.py
> +    assert items[1] == expected_resp[1], items
Yes, we are comparing the status codes of items and expected_resp. 

Items after expected_resp prints you the items in terminal if the assert fails.Example below
FAILED test_search.py::test_for_multiple_version - AssertionError: ({'data': [{'ci_version': 1, 'data_version': '1', 'form_type': 't', 'language': 'em', ...}], 'status': 'success'}, 200)

Without the items it will look like this
FAILED test_search.py::test_for_multiple_version - assert 200 != 200

2023-02-23 10:03 UTC, aljaplatt commented on handlers/tests/test_search.py
> +    assert items[1] == expected_resp[1], items
Right, ok cool thanks Sri, makes sense now.

2023-02-23 10:28 UTC, mateen-hussain commented on .gcloudignore
> +gateway
Did you merge main with your branch? All these changes are already in main.

2023-02-23 10:56 UTC, mateen-hussain requested changes
Please update your branch with main, as it is hard to see which changes are yours and which ones are already in main

2023-02-23 12:48 UTC, mateen-hussain commented on handlers/tests/test_search.py
> +from datetime import datetime
You can merge this file with test_search, or rename this file to reflect the method you are testing, ex `test_query_ci.py`. If renaming then rename the other `test_collection_instrument` to `test_publish_ci`.

2023-02-23 12:53 UTC, mateen-hussain commented on handlers/tests/test_search.py
> +def test_not_available(mocker):
test names should be descriptive and specific. For ex `test_not_available` doesnt tell me what is not available? Maybe a more specific name like `test_query_ci_returns_ci_not_found_when_querying_for_non_existent_ci`

2023-02-23 12:54 UTC, mateen-hussain commented on handlers/tests/test_search.py
> +class MockRequest:
This `MockRequest` object is repeated in more than one file. Maybe put it in a common file under `tests` folder and it can be shared across other tests in that folder.

2023-02-23 12:58 UTC, mateen-hussain commented on handlers/tests/test_search.py
> +    assert items[0]['status'] == expected_resp[0]['status']
This is an overkill. Just mock `datetime` to return the same value and you can simply compare `response == expected_resp`. Always be careful in nested for loops and if conditions, avoid wherever possible. As this is the cause of most bugs :)

2023-02-23 13:00 UTC, mateen-hussain commented on handlers/tests/test_search.py
> +    # Reason for multiple conditions in the assertion: the metadata
If you mock datetime correctly then your expected response and actual response will have the same `published_at` and you can avoid doing the conditional asserts.

Check `test_publish_ci_appends_new_version_to_existing_ci_and_returns_200` test

2023-02-23 14:36 UTC, SriHV commented on .gcloudignore
> +gateway
Yes, I have merged main into my branch

2023-02-23 15:32 UTC, SriHV commented on handlers/tests/test_search.py
> +from datetime import datetime
Renamed

2023-02-24 11:00 UTC, closed without merging